### ISSUE TITLE
apostrophe passport failing

### ISSUE THREAD

**Issue by thecb4** [apostrophecms/apostrophe-passport#1]
Trying to get started with Apostrophe and having issues getting passport working. And getting the following issue

    "apostrophe": "^2.0.0",
    "apostrophe-passport": "^2.0.0",
    "passport-gitlab2": "^3.0.0",
    "passport-twitter": "^1.0.4"

    // login strategies
    'apostrophe-passport': {
      strategies: [
        {
          module: 'passport-twitter',
          options: {
            consumerKey: 'CONSUMER_KEY',
            consumerSecret: 'CONSUMER_SECRET,
          }
        }
      ]
    }

source/node_modules/express/lib/router/route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as get] (source/node_modules/express/lib/router/route.js:202:15)
    at Function.app.(anonymous function) [as get] (source/node_modules/express/lib/application.js:482:19)
    at Object.self.addCallbackRoute (source/node_modules/apostrophe-passport/index.js:80:21)
    at source/node_modules/apostrophe-passport/index.js:53:14
    at arrayEach (source/node_modules/apostrophe-passport/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (source/node_modules/apostrophe-passport/node_modules/lodash/lodash.js:9359:14)
    at Object.self.enablePassportStrategies (source/node_modules/apostrophe-passport/index.js:21:9)
    at afterConstruct (source/node_modules/apostrophe-passport/index.js:7:10)
    at /source/node_modules/moog/index.js:300:22
    at iterate (source/node_modules/moog/node_modules/async/lib/async.js:146:13)
    at Immediate._onImmediate (source/node_modules/moog/node_modules/async/lib/async.js:157:25)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

**Comment by thecb4** [comment]
Looks like apostrophe-login didn't have a 'afterLogin' method
        // actual route
        self.apos.login.afterLogin

seems like copying the method from the apostrophe-login fixes the issue
    self.afterLogin =         function(req, res) {
              return self.apos.callAll('loginAfterLogin', req, function(err) {
                req.redirect = req.redirect || '/';
                return res.redirect(req.redirect);
              });
            }

**Comment by boutell** [comment]
Is your apostrophe module up to date? This was a recent introduction.

**Comment by thecb4** [comment]
Thanks for the response so late. Seems like deleting the package-locked.json and reinstalling picked up the update.

**Comment by boutell** [comment]
Great. Next time just use npm update

**Comment by thecb4** [comment]
Will do. Thank you for the help. 
Happy Monday!

Cheers,
CB
